steps:
- name: 'gcr.io/cloud-builders/gcloud'
  script: |
    gcloud run deploy "chat-flask-app" --image us-docker.pkg.dev/cloudrun/container/hello --region us-central1 --platform managed --allow-unauthenticated --project qwiklabs-gcp-02-1bc482e73ab0
